#!/bin/sh

if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  echo "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [[ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-aliases-exa" ]]; then
  echo "Installing plugin zsh-aliases-exa"
  git clone https://github.com/DarrinTisdale/zsh-aliases-exa $HOME/.oh-my-zsh/custom/plugins/zsh-aliases-exa
fi


if [[ ! -d "$HOME/.oh-my-zsh/custom/plugins/you-should-use" ]]; then
  echo "Installing plugin you-should-use"
  git clone https://github.com/MichaelAquilina/zsh-you-should-use $HOME/.oh-my-zsh/custom/plugins/you-should-use
fi

if [[ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]]; then
  echo "Installing plugin zsh-autosuggestions"
  git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
fi

if [[ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-completions" ]]; then
  echo "Installing plugin zsh-completions"
  git clone https://github.com/zsh-users/zsh-completions $HOME/.oh-my-zsh/custom/plugins/zsh-completions
fi

if [[ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]]; then
  echo "Installing plugin zsh-syntax-highlighting"
  git clone https://github.com/zsh-users/zsh-syntax-highlighting $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
fi

echo "Updating homebrew bundle"
brew upgrade
brew bundle --global

echo "Decrypt dotfiles"
yadm decrypt

echo "Updating the yadm repo origin URL to use SSH"
yadm remote set-url origin "git@github.com:eckertalex/dotfiles.git"

echo "Install Volta"
curl https://get.volta.sh | bash

echo "Install Node"
volta install node

echo "Installing trash-cli"
npm install --global trash-cli

echo "Install dependencies for ranger"
python -m pip install Pillow
python -m pip install chardet

echo "Configure MacOS"
/bin/bash ~/.macos

echo "Done!"
