default_flags = "hd"
cols_order = "scdgbn"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
key = "enter"
leave_broot = false
execution = "git difftool -y {file}"
apply_to = "file"

[[verbs]]
invocation = "git_add"
shortcut = "ga"
key = "ctrl-a"
leave_broot = false
execution = "git add {file}"
apply_to = "file"

[[verbs]]
invocation = "git_checkout"
shortcut = "gco"
leave_broot = false
execution = "git checkout {file}"
apply_to = "file"
